-- ===========================================================================
-- POC v2  —  S06  |  A value corrected with no change to its dates
--
-- Zone1 restates a value over exactly the same interval. The hash moves, both
-- dates stay, and the target row sits at the high end date -- the definition
-- of rule 9, which retires by DEAD RECORD rather than delete indicator.
--
-- HOW THIS SCENARIO IS STRUCTURED
--
-- The target is NEVER hand-seeded. TC01 loads an empty target through the real
-- pipeline, and every later test case is the NEXT RUN against whatever the
-- previous one left behind -- which is what a real ETL schedule does, and the
-- only way to test that older rows stay untouched.
--
-- There is ONE reset, at the top of this file. Test cases do not reset. They
-- must therefore be run IN ORDER, top to bottom; each is still a self-contained
-- section to execute and screenshot. Scenarios are independent of each other.
--
-- TWO CLOCKS:
--   BUSINESS TIME  ROW_EFF_DTE / ROW_EXP_DTE -- when the fact was true
--   PROCESS TIME   GRS_REFINED_TIMESTAMP, windows, AUDIT_* -- when it was loaded
--
-- Windows are half-open: GRS_REFINED_TIMESTAMP > WINDOW_START AND <= WINDOW_END.
-- Three runs a day, 08:00 / 12:00 / 16:00.
--
--   TC01  D1R1  run 101   window  2026-09-01 00:00 -> 2026-09-21 08:00
--   TC02  D1R2  run 102   window  2026-09-21 08:00 -> 2026-09-21 12:00
--   TC03  D1R3  run 103   window  2026-09-21 08:00 -> 2026-09-21 12:00  (re-run)
--   TC04  D2R1  run 104   window  2026-09-21 16:00 -> 2026-09-22 08:00
--
-- Rules exercised : see ../TEST_PLAN.md
-- Prerequisite    : ../00_objects.sql has been run
-- ===========================================================================

USE ROLE      POC_ROLE;
USE WAREHOUSE POC_WH;
USE DATABASE  LM_POC_DB;
USE SCHEMA    POC_SCHEMA;


-- ###########################################################################
-- RESET -- the ONLY one in this file. Everything after this accumulates.
-- The surrogate-key sequence is deliberately NOT reset: production never
-- reuses a key, so neither do we. See ../TEST_PLAN.md.
-- ###########################################################################
TRUNCATE TABLE ETL_DATA_INGESTION_SOURCE_WINDOW;
TRUNCATE TABLE Z1_BROKER_PARTY_HIST;
TRUNCATE TABLE Z1_BROKER_COMMISSION_HIST;
TRUNCATE TABLE Z2_BROKER_PARTY_DIM;
TRUNCATE TABLE STG_Z2_BROKER_PARTY_DIM;


-- ###########################################################################
-- TC01  (D1R1)  |  POSITIVE  |  initial load into an empty target
--
-- WHAT   One version in each source.
-- EXPECT 1 stage row, rule 17. Target 0 -> 1.
-- ###########################################################################

INSERT INTO ETL_DATA_INGESTION_SOURCE_WINDOW
 (EXECUTION_RUN_ID, JOB_RUN_ID, TARGET_TABLE_NAME, SOURCE_TABLE_NAME,
  WINDOW_START, WINDOW_END, EXECUTION_TYPE, JOB_STATUS)
VALUES
 (101,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_PARTY_HIST',
  TIMESTAMP '2026-09-01 00:00', TIMESTAMP '2026-09-21 08:00','NEW','Completed'),
 (101,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_COMMISSION_HIST',
  TIMESTAMP '2026-09-01 00:00', TIMESTAMP '2026-09-21 08:00','NEW','Completed');

-- ---- what Zone1 did between the last run and this one -------------------
INSERT INTO Z1_BROKER_PARTY_HIST
SELECT    'K1','A1',NULL,DATE '2026-08-10',DATE '9999-12-31','U-001',TIMESTAMP '2026-09-21 08:00';
INSERT INTO Z1_BROKER_COMMISSION_HIST
SELECT    'K1','B1',NULL,DATE '2026-08-10',DATE '9999-12-31','U-101',TIMESTAMP '2026-09-21 08:00';

SELECT 'S06 TC01 D1R1 — SRC_1' AS EVIDENCE, BROKER_ID, BROKER_STATUS_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_PARTY_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC01 D1R1 — SRC_2' AS EVIDENCE, BROKER_ID, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_COMMISSION_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

-- ---- STEP 1 : build the stage --------------------------------------------
TRUNCATE TABLE STG_Z2_BROKER_PARTY_DIM;
INSERT INTO STG_Z2_BROKER_PARTY_DIM SELECT * FROM V_STEP1_BROKER_PARTY_DIM_DIFF;

SELECT 'S06 TC01 D1R1 — stage' AS EVIDENCE, RULE_NO, ACTION_FLAG, DEL_IND,
       BROKER_PARTY_DIM_SK, BROKER_ID, BROKER_STATUS_CDE, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE
FROM   STG_Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, ACTION_FLAG;

-- ---- STEP 2 : apply, one atomic MERGE ------------------------------------
MERGE INTO Z2_BROKER_PARTY_DIM T
USING STG_Z2_BROKER_PARTY_DIM S
   ON  T.BROKER_PARTY_DIM_SK = S.BROKER_PARTY_DIM_SK
   AND S.ACTION_FLAG <> 'I'          -- 'I' rows can never match, whatever SK they carry
WHEN MATCHED AND S.ACTION_FLAG = 'U' THEN UPDATE SET
     T.ROW_EXP_DTE           = S.ROW_EXP_DTE,
     T.UUID                  = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN MATCHED AND S.ACTION_FLAG = 'D' THEN UPDATE SET
     T.IS_DEL      = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.IS_DEL ELSE 'Y' END,
     T.ROW_EXP_DTE = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.ROW_EFF_DTE ELSE T.ROW_EXP_DTE END,
     T.UUID        = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
     BROKER_PARTY_DIM_SK, BROKER_ID, ROW_EFF_DTE, ROW_EXP_DTE,
     BROKER_STATUS_CDE, COMMISSION_TIER_CDE, IS_DEL, ROW_HASH, UUID,
     AUDIT_BATCH_ID, AUDIT_JOB_ID, AUDIT_CREATE_DATETIME, AUDIT_UPDATE_DATETIME)
VALUES (
     S.BROKER_PARTY_DIM_SK, S.BROKER_ID, S.ROW_EFF_DTE, S.ROW_EXP_DTE,
     S.BROKER_STATUS_CDE, S.COMMISSION_TIER_CDE, 'N', S.ROW_HASH, S.UUID,
     S.AUDIT_BATCH_ID, S.AUDIT_JOB_ID, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ---- verify ---------------------------------------------------------------
SELECT 'S06 TC01 D1R1 — target AFTER' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE, IS_DEL, AUDIT_BATCH_ID
FROM   Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, BROKER_PARTY_DIM_SK;

SELECT 'S06 TC01 D1R1 — live view' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE
FROM   V_Z2_BROKER_PARTY_DIM_LIVE ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC01 D1R1' AS TEST,
       CASE WHEN (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM)  = 1
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM) = 1
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE) = 1
       THEN 'PASS' ELSE 'FAIL' END AS RESULT;


-- ###########################################################################
-- TC02  (D1R2)  |  POSITIVE  |  the value is corrected, both dates unchanged
--
-- WHAT   B1 becomes B5 over exactly the same interval.
-- EXPECT 2 stage rows, rule 9. The old row becomes a DEAD RECORD -- expiry pulled back to its own effective date, IS_DEL left at 'N'. Target 1 -> 2, live stays 1.
-- ###########################################################################

INSERT INTO ETL_DATA_INGESTION_SOURCE_WINDOW
 (EXECUTION_RUN_ID, JOB_RUN_ID, TARGET_TABLE_NAME, SOURCE_TABLE_NAME,
  WINDOW_START, WINDOW_END, EXECUTION_TYPE, JOB_STATUS)
VALUES
 (102,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_PARTY_HIST',
  TIMESTAMP '2026-09-21 08:00', TIMESTAMP '2026-09-21 12:00','NEW','Completed'),
 (102,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_COMMISSION_HIST',
  TIMESTAMP '2026-09-21 08:00', TIMESTAMP '2026-09-21 12:00','NEW','Completed');

-- ---- what Zone1 did between the last run and this one -------------------
UPDATE Z1_BROKER_COMMISSION_HIST
SET    COMMISSION_TIER_CDE = 'B5', GRS_REFINED_TIMESTAMP = TIMESTAMP '2026-09-21 12:00'
WHERE  BROKER_ID = 'K1' AND ROW_EFF_DTE = DATE '2026-08-10';

SELECT 'S06 TC02 D1R2 — SRC_1' AS EVIDENCE, BROKER_ID, BROKER_STATUS_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_PARTY_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC02 D1R2 — SRC_2' AS EVIDENCE, BROKER_ID, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_COMMISSION_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

-- ---- STEP 1 : build the stage --------------------------------------------
TRUNCATE TABLE STG_Z2_BROKER_PARTY_DIM;
INSERT INTO STG_Z2_BROKER_PARTY_DIM SELECT * FROM V_STEP1_BROKER_PARTY_DIM_DIFF;

SELECT 'S06 TC02 D1R2 — stage' AS EVIDENCE, RULE_NO, ACTION_FLAG, DEL_IND,
       BROKER_PARTY_DIM_SK, BROKER_ID, BROKER_STATUS_CDE, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE
FROM   STG_Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, ACTION_FLAG;

-- ---- STEP 2 : apply, one atomic MERGE ------------------------------------
MERGE INTO Z2_BROKER_PARTY_DIM T
USING STG_Z2_BROKER_PARTY_DIM S
   ON  T.BROKER_PARTY_DIM_SK = S.BROKER_PARTY_DIM_SK
   AND S.ACTION_FLAG <> 'I'          -- 'I' rows can never match, whatever SK they carry
WHEN MATCHED AND S.ACTION_FLAG = 'U' THEN UPDATE SET
     T.ROW_EXP_DTE           = S.ROW_EXP_DTE,
     T.UUID                  = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN MATCHED AND S.ACTION_FLAG = 'D' THEN UPDATE SET
     T.IS_DEL      = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.IS_DEL ELSE 'Y' END,
     T.ROW_EXP_DTE = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.ROW_EFF_DTE ELSE T.ROW_EXP_DTE END,
     T.UUID        = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
     BROKER_PARTY_DIM_SK, BROKER_ID, ROW_EFF_DTE, ROW_EXP_DTE,
     BROKER_STATUS_CDE, COMMISSION_TIER_CDE, IS_DEL, ROW_HASH, UUID,
     AUDIT_BATCH_ID, AUDIT_JOB_ID, AUDIT_CREATE_DATETIME, AUDIT_UPDATE_DATETIME)
VALUES (
     S.BROKER_PARTY_DIM_SK, S.BROKER_ID, S.ROW_EFF_DTE, S.ROW_EXP_DTE,
     S.BROKER_STATUS_CDE, S.COMMISSION_TIER_CDE, 'N', S.ROW_HASH, S.UUID,
     S.AUDIT_BATCH_ID, S.AUDIT_JOB_ID, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ---- verify ---------------------------------------------------------------
SELECT 'S06 TC02 D1R2 — target AFTER' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE, IS_DEL, AUDIT_BATCH_ID
FROM   Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, BROKER_PARTY_DIM_SK;

SELECT 'S06 TC02 D1R2 — live view' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE
FROM   V_Z2_BROKER_PARTY_DIM_LIVE ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC02 D1R2' AS TEST,
       CASE WHEN (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM)  = 2
                   AND (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM WHERE RULE_NO = 9) = 2
                   AND (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM WHERE ACTION_FLAG = 'D') = 1
                   AND (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM WHERE ACTION_FLAG = 'I') = 1
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM) = 2
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE) = 1
            -- DEAD RECORD: eff = exp, and IS_DEL is still 'N'
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM WHERE ROW_EFF_DTE = DATE '2026-08-10' AND ROW_EXP_DTE = DATE '2026-08-10'
                      AND IS_DEL = 'N' AND COMMISSION_TIER_CDE = 'B1') = 1
            -- nothing was retired by delete indicator
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM WHERE IS_DEL = 'Y') = 0
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE WHERE COMMISSION_TIER_CDE = 'B5') = 1
       THEN 'PASS' ELSE 'FAIL' END AS RESULT;


-- ###########################################################################
-- TC03  (D1R3)  |  IDEMPOTENT  |  re-run of the same window
--
-- WHAT   The dead record must not re-enter the diff. If the target read forgot its eff < exp filter, this run would see two rows at one effective date.
-- EXPECT 0 stage rows.
-- ###########################################################################

INSERT INTO ETL_DATA_INGESTION_SOURCE_WINDOW
 (EXECUTION_RUN_ID, JOB_RUN_ID, TARGET_TABLE_NAME, SOURCE_TABLE_NAME,
  WINDOW_START, WINDOW_END, EXECUTION_TYPE, JOB_STATUS)
VALUES
 (103,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_PARTY_HIST',
  TIMESTAMP '2026-09-21 08:00', TIMESTAMP '2026-09-21 12:00','NEW','Completed'),
 (103,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_COMMISSION_HIST',
  TIMESTAMP '2026-09-21 08:00', TIMESTAMP '2026-09-21 12:00','NEW','Completed');

-- ---- NO source change. This run re-reads the same window ----------------

SELECT 'S06 TC03 D1R3 — SRC_1' AS EVIDENCE, BROKER_ID, BROKER_STATUS_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_PARTY_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC03 D1R3 — SRC_2' AS EVIDENCE, BROKER_ID, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_COMMISSION_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

-- ---- STEP 1 : build the stage --------------------------------------------
TRUNCATE TABLE STG_Z2_BROKER_PARTY_DIM;
INSERT INTO STG_Z2_BROKER_PARTY_DIM SELECT * FROM V_STEP1_BROKER_PARTY_DIM_DIFF;

SELECT 'S06 TC03 D1R3 — stage' AS EVIDENCE, RULE_NO, ACTION_FLAG, DEL_IND,
       BROKER_PARTY_DIM_SK, BROKER_ID, BROKER_STATUS_CDE, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE
FROM   STG_Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, ACTION_FLAG;

-- ---- STEP 2 : apply, one atomic MERGE ------------------------------------
MERGE INTO Z2_BROKER_PARTY_DIM T
USING STG_Z2_BROKER_PARTY_DIM S
   ON  T.BROKER_PARTY_DIM_SK = S.BROKER_PARTY_DIM_SK
   AND S.ACTION_FLAG <> 'I'          -- 'I' rows can never match, whatever SK they carry
WHEN MATCHED AND S.ACTION_FLAG = 'U' THEN UPDATE SET
     T.ROW_EXP_DTE           = S.ROW_EXP_DTE,
     T.UUID                  = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN MATCHED AND S.ACTION_FLAG = 'D' THEN UPDATE SET
     T.IS_DEL      = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.IS_DEL ELSE 'Y' END,
     T.ROW_EXP_DTE = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.ROW_EFF_DTE ELSE T.ROW_EXP_DTE END,
     T.UUID        = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
     BROKER_PARTY_DIM_SK, BROKER_ID, ROW_EFF_DTE, ROW_EXP_DTE,
     BROKER_STATUS_CDE, COMMISSION_TIER_CDE, IS_DEL, ROW_HASH, UUID,
     AUDIT_BATCH_ID, AUDIT_JOB_ID, AUDIT_CREATE_DATETIME, AUDIT_UPDATE_DATETIME)
VALUES (
     S.BROKER_PARTY_DIM_SK, S.BROKER_ID, S.ROW_EFF_DTE, S.ROW_EXP_DTE,
     S.BROKER_STATUS_CDE, S.COMMISSION_TIER_CDE, 'N', S.ROW_HASH, S.UUID,
     S.AUDIT_BATCH_ID, S.AUDIT_JOB_ID, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ---- verify ---------------------------------------------------------------
SELECT 'S06 TC03 D1R3 — target AFTER' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE, IS_DEL, AUDIT_BATCH_ID
FROM   Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, BROKER_PARTY_DIM_SK;

SELECT 'S06 TC03 D1R3 — live view' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE
FROM   V_Z2_BROKER_PARTY_DIM_LIVE ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC03 D1R3' AS TEST,
       CASE WHEN (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM)  = 0
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM) = 2
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE) = 1
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM WHERE AUDIT_BATCH_ID = 103) = 0
       THEN 'PASS' ELSE 'FAIL' END AS RESULT;


-- ###########################################################################
-- TC04  (D2R1)  |  EDGE  |  corrected to NULL
--
-- WHAT   B5 is restated as NULL -- a correction TO absence, which the hash must treat as a change.
-- EXPECT 2 stage rows, rule 9 again. Target 2 -> 3, live stays 1 and now carries no tier.
-- ###########################################################################

INSERT INTO ETL_DATA_INGESTION_SOURCE_WINDOW
 (EXECUTION_RUN_ID, JOB_RUN_ID, TARGET_TABLE_NAME, SOURCE_TABLE_NAME,
  WINDOW_START, WINDOW_END, EXECUTION_TYPE, JOB_STATUS)
VALUES
 (104,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_PARTY_HIST',
  TIMESTAMP '2026-09-21 16:00', TIMESTAMP '2026-09-22 08:00','NEW','Completed'),
 (104,1,'Z2_BROKER_PARTY_DIM','Z1_BROKER_COMMISSION_HIST',
  TIMESTAMP '2026-09-21 16:00', TIMESTAMP '2026-09-22 08:00','NEW','Completed');

-- ---- what Zone1 did between the last run and this one -------------------
UPDATE Z1_BROKER_COMMISSION_HIST
SET    COMMISSION_TIER_CDE = NULL, GRS_REFINED_TIMESTAMP = TIMESTAMP '2026-09-22 08:00'
WHERE  BROKER_ID = 'K1' AND ROW_EFF_DTE = DATE '2026-08-10';

SELECT 'S06 TC04 D2R1 — SRC_1' AS EVIDENCE, BROKER_ID, BROKER_STATUS_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_PARTY_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC04 D2R1 — SRC_2' AS EVIDENCE, BROKER_ID, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE, GRS_REFINED_TIMESTAMP
FROM   Z1_BROKER_COMMISSION_HIST ORDER BY BROKER_ID, ROW_EFF_DTE;

-- ---- STEP 1 : build the stage --------------------------------------------
TRUNCATE TABLE STG_Z2_BROKER_PARTY_DIM;
INSERT INTO STG_Z2_BROKER_PARTY_DIM SELECT * FROM V_STEP1_BROKER_PARTY_DIM_DIFF;

SELECT 'S06 TC04 D2R1 — stage' AS EVIDENCE, RULE_NO, ACTION_FLAG, DEL_IND,
       BROKER_PARTY_DIM_SK, BROKER_ID, BROKER_STATUS_CDE, COMMISSION_TIER_CDE,
       ROW_EFF_DTE, ROW_EXP_DTE
FROM   STG_Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, ACTION_FLAG;

-- ---- STEP 2 : apply, one atomic MERGE ------------------------------------
MERGE INTO Z2_BROKER_PARTY_DIM T
USING STG_Z2_BROKER_PARTY_DIM S
   ON  T.BROKER_PARTY_DIM_SK = S.BROKER_PARTY_DIM_SK
   AND S.ACTION_FLAG <> 'I'          -- 'I' rows can never match, whatever SK they carry
WHEN MATCHED AND S.ACTION_FLAG = 'U' THEN UPDATE SET
     T.ROW_EXP_DTE           = S.ROW_EXP_DTE,
     T.UUID                  = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN MATCHED AND S.ACTION_FLAG = 'D' THEN UPDATE SET
     T.IS_DEL      = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.IS_DEL ELSE 'Y' END,
     T.ROW_EXP_DTE = CASE WHEN T.ROW_EXP_DTE = DATE '9999-12-31'
                          THEN T.ROW_EFF_DTE ELSE T.ROW_EXP_DTE END,
     T.UUID        = COALESCE(S.UUID, T.UUID),
     T.AUDIT_UPDATE_DATETIME = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
     BROKER_PARTY_DIM_SK, BROKER_ID, ROW_EFF_DTE, ROW_EXP_DTE,
     BROKER_STATUS_CDE, COMMISSION_TIER_CDE, IS_DEL, ROW_HASH, UUID,
     AUDIT_BATCH_ID, AUDIT_JOB_ID, AUDIT_CREATE_DATETIME, AUDIT_UPDATE_DATETIME)
VALUES (
     S.BROKER_PARTY_DIM_SK, S.BROKER_ID, S.ROW_EFF_DTE, S.ROW_EXP_DTE,
     S.BROKER_STATUS_CDE, S.COMMISSION_TIER_CDE, 'N', S.ROW_HASH, S.UUID,
     S.AUDIT_BATCH_ID, S.AUDIT_JOB_ID, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ---- verify ---------------------------------------------------------------
SELECT 'S06 TC04 D2R1 — target AFTER' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE, IS_DEL, AUDIT_BATCH_ID
FROM   Z2_BROKER_PARTY_DIM ORDER BY BROKER_ID, ROW_EFF_DTE, BROKER_PARTY_DIM_SK;

SELECT 'S06 TC04 D2R1 — live view' AS EVIDENCE, BROKER_PARTY_DIM_SK, BROKER_ID,
       BROKER_STATUS_CDE, COMMISSION_TIER_CDE, ROW_EFF_DTE, ROW_EXP_DTE
FROM   V_Z2_BROKER_PARTY_DIM_LIVE ORDER BY BROKER_ID, ROW_EFF_DTE;

SELECT 'S06 TC04 D2R1' AS TEST,
       CASE WHEN (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM)  = 2
                   AND (SELECT count(*) FROM STG_Z2_BROKER_PARTY_DIM WHERE RULE_NO = 9) = 2
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM) = 3
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE) = 1
            -- the live row now carries NO tier
                   AND (SELECT count(*) FROM V_Z2_BROKER_PARTY_DIM_LIVE WHERE COMMISSION_TIER_CDE IS NULL) = 1
            -- two dead records now, one per correction
                   AND (SELECT count(*) FROM Z2_BROKER_PARTY_DIM WHERE ROW_EFF_DTE = ROW_EXP_DTE AND IS_DEL = 'N') = 2
       THEN 'PASS' ELSE 'FAIL' END AS RESULT;
